//CONTRUCTION
export const CONTRUCTION_BEGIN = "CONTRUCTION_BEGIN";
export const CONTRUCTION_SUCCESS = "CONTRUCTION_SUCCESS";
export const CONTRUCTION_ERROR = "CONTRUCTION_ERROR";
export const CONTRUCTION_CREATE_BEGIN = "CONTRUCTION_CREATE_BEGIN";
export const CONTRUCTION_CREATE_SUCCESS = "CONTRUCTION_CREATE_SUCCESS";
export const CONTRUCTION_CREATE_ERROR = "CONTRUCTION_CREATE_ERROR";

//ORDER
export const GET_ORDER_BEGIN = "GET_ORDER_BEGIN";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";
export const CREATE_ORDER_BEGIN = "CREATE_ORDER_BEGIN";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";
export const EDIT_ORDER_BEGIN = "EDIT_ORDER_BEGIN";
export const EDIT_ORDER_SUCCESS = "EDIT_ORDER_SUCCESS";
export const EDIT_ORDER_ERROR = "EDIT_ORDER_ERROR";

// ALERT
export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// (Register/login/Update) User
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

// SIDEBAR
export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

// Job
export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";
// export const GET_JOBS_ERROR = "GET_JOBS_ERROR";

export const GET_REQUEST_BEGIN = "GET_REQUEST_BEGIN";
export const GET_REQUEST_SUCCESS = "GET_REQUEST_SUCCESS";

export const SET_EDIT_JOB = "SET_EDIT_JOB";
export const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

export const DELETE_JOB_BEGIN = "DELETE_JOB_BEGIN";

export const SHOW_STATS_BEGIN = "SHOW_STATS_BEGIN";
export const SHOW_STATS_SUCCESS = "SHOW_STATS_SUCCESS";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";


// CLEAR ALL ALERT
export const CLEAR_ALL_ALERT = "CLEAR_ALL_ALERT"